default: &base
  version: 4.0.0.beta4
  register_enabled: <%= ENV['ZEALOT_REGISTER_ENABLED'] || 'true' %>
  cron_jobs:
    clean_old_releases:
      cron: '0 6 * * *'
      class: 'CleanOldReleasesJob'
      queue: schedule
    reset_for_demo_mode:
      cron: '0 0 * * *'
      class: 'ResetForDemoModeJob'
      queue: schedule

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base